version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ctycho-s3.ru
    volumes:
      - ./data:/data
      - ./config:/root/.minio
      - /home/vmadmin/development/minIO/.minio/certs/ctycho-s3.key:/root/.minio/certs/public.key
      - /home/vmadmin/development/minIO/.minio/certs/ctycho-s3.crt:/root/.minio/certs/private.crt
    command: server /data --console-address ":9001"
    restart: always